name: 3D Contribution Skyline

on:
  schedule:
    - cron: "0 0 * * *" # runs once a day
  workflow_dispatch: # lets you trigger it manually anytime

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: anya2407
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git commit -m "Update 3D contribution skyline" || exit 0
          git push
